CREATE TABLE COURSE(CNO INT PRIMARY KEY , CNAME TEXT);

ALTER TABLE COURSE ADD COLUMN CREDIT INT;

SELECT * FROM COURSE;

ALTER TABLE COURSE DROP COLUMN CREDIT;

ALTER TABLE COURSE ADD CONSTRAINT CHE CHECK(CREDIT>10);

DROP TABLE COURSE;

// COURSE IS THE NAME OF DATABASE


