CREATE TABLE COURSE(CNO INT PRIMARY KEY , CNAME TEXT);

ALTER TABLE COURSE ADD COLUMN CREDIT INT;

SELECT * FROM COURSE;

ALTER TABLE COURSE DROP COLUMN CREDIT;

ALTER TABLE COURSE ADD CONSTRAINT CHE CHECK(CREDIT>10);

DROP TABLE COURSE;

/* COURSE IS THE NAME OF DATABASE*/

/* VARCHAR(15) MEANS IT CAN BE OF ANYY LENGTH FROM 1 TO 15*/

/* DML => DATA MANIPULAION LANGUAGE */
/* DATE FORMAT => YYYY-MM-DD */

INSERT INTO EMPLOYEE VALUES()
